### ISSUE TITLE
$50 - fix a shader bug in HaxeFlixel

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/larsBounties#4]
**The Project**

Pretty much entirely described on its own issue page over at HaxeFlixel:
https://github.com/HaxeFlixel/flixel/issues/2192

Fix this bug if you can!

**Prerequisites**

* Knowledge of HaxeFlixel
* Knowledge of OpenFL
* Knowledge of shaders

**What's been done so far**

See the issue. I have a repro sample and some basic legwork as to where the bug originates.

**How much can Lars help**

Available to answer questions and chat and stuff. I obviously can't solve this myself, but I can point you to where I think the problem is and bounce ideas off.

**What remains to be done**

Fix the bug!

**Budget/Timeline**

Would really like this done ASAP. A week or two ideally. A month is about my max. Sooner = better.

Budget is $50 USD.

**Comment by JoeCreates** [comment]
I've been having a look at this this morning. Have made some progress. Not everything is clear yet, but of what I have found, my findings will surprise you. :P

**Comment by JoeCreates** [comment]
Okay, so things are sorted, now.

**Comment by larsiusprime** [comment]
Really? Is it true? Really and truly?

**Comment by larsiusprime** [comment]
Claimed and fixed by @JoeCreates . $50 bounty paid, a job well done!
